In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv(r"C:\Users\tyagi\OneDrive\Desktop\Pokemash 3\Tryout\Training.csv", delimiter=';', on_bad_lines='skip')
df.head()

,track_id,track_name,track_popularity,track_number,album_id,album_name,album_img,album_type,album_label,album_track_number,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,pivot,streams,track_index
0,5aAx2yezTd8zXrkmtKl66Z,Starboy,0,1,09fggMHib4YkOtwQNXEBII,Starboy,https://i.scdn.co/image/ab67616d0000b2730c8599...,album,Universal Music Group,1,...,0.2820,0.165,0.000003,0.134,0.535,186.054,230453,0,25734078,1
1,5aAx2yezTd8zXrkmtKl66Z,Starboy,0,1,09fggMHib4YkOtwQNXEBII,Starboy,https://i.scdn.co/image/ab67616d0000b2730c8599...,album,Universal Music Group,1,...,0.2820,0.165,0.000003,0.134,0.535,186.054,230453,1,25734078,1
2,7BKLCZ1jbUBVqRi2FVlTVw,Closer,84,1,0rSLgV8p5FzfnqlEk4GzxE,Closer,https://i.scdn.co/image/ab67616d0000b273495ce6...,single,Disruptor Records/Columbia,1,...,0.0338,0.414,0.000000,0.111,0.661,95.010,244960,0,23519705,2
3,7BKLCZ1jbUBVqRi2FVlTVw,Closer,84,1,0rSLgV8p5FzfnqlEk4GzxE,Closer,https://i.scdn.co/image/ab67616d0000b273495ce6...,single,Disruptor Records/Columbia,1,...,0.0338,0.414,0.000000,0.111,0.661,95.010,244960,1,23519705,2
4,5knuzwU65gJK7IF5yJsuaW,Rockabye (feat. Sean Paul & Anne-Marie),75,1,3meZFplbMmji648oWUNEfQ,Rockabye (feat. Sean Paul & Anne-Marie),https://i.scdn.co/image/ab67616d0000b2731431c3...,single,Atlantic Records UK,1,...,0.0523,0.406,0.000000,0.180,0.742,101.965,251088,0,21216399,3

In [9]:
# df.to_csv(r"C:\Users\tyagi\OneDrive\Desktop\Pokemash 3\Tryout\Training.csv", index=False)

In [10]:
df.describe()

,track_popularity,track_number,album_track_number,album_popularity,artist_num,artist_followers,artist_popularity,rank,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,pivot,streams,track_index
count,74660.000000,74660.000000,74660.000000,74660.000000,74660.000000,7.466000e+04,74660.000000,74660.000000,74660.000000,74660.000000,...,74660.000000,74660.000000,74660.000000,74660.000000,74660.000000,74660.000000,74660.000000,74660.000000,7.466000e+04,74660.000000
mean,57.851661,3.843892,3.843892,52.386244,2.233003,1.992528e+07,79.868711,99.574819,0.707997,0.651976,...,0.119321,0.217359,0.005648,0.167878,0.520031,120.762263,212258.769796,0.407983,8.336837e+06,21867.919314
std,29.514677,4.390576,4.390576,27.851247,1.320795,2.264422e+07,9.941376,57.293789,0.127662,0.152462,...,0.100752,0.219920,0.044550,0.122673,0.218686,29.824768,44088.043199,0.491463,5.698289e+06,12608.146829
min,0.000000,1.000000,1.000000,0.000000,1.000000,4.000000e+00,0.000000,1.000000,0.150000,0.027900,...,0.023200,0.000025,0.000000,0.019700,0.032000,46.718000,30133.000000,0.000000,2.525159e+06,1.000000
25%,57.000000,1.000000,1.000000,47.000000,1.000000,3.639519e+06,75.000000,50.000000,0.637000,0.552000,...,0.047600,0.048400,0.000000,0.093600,0.352000,96.172000,184560.000000,0.000000,4.945827e+06,10951.750000
50%,71.000000,1.000000,1.000000,62.000000,2.000000,1.065244e+07,81.000000,99.000000,0.727000,0.669000,...,0.077400,0.145000,0.000000,0.123000,0.518000,115.017500,207232.500000,0.000000,6.333818e+06,21846.000000
75%,77.000000,5.000000,5.000000,72.000000,3.000000,2.993942e+07,87.000000,149.000000,0.796000,0.769000,...,0.155000,0.310000,0.000012,0.196000,0.690000,140.060000,231906.000000,1.000000,9.642750e+06,32528.000000
max,92.000000,76.000000,76.000000,86.000000,11.000000,1.040598e+08,100.000000,200.000000,0.980000,0.978000,...,0.966000,0.994000,0.953000,0.962000,0.982000,212.117000,577199.000000,1.000000,8.076404e+07,44200.000000

In [12]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.99)
train.describe()

,track_popularity,track_number,album_track_number,album_popularity,artist_num,artist_followers,artist_popularity,rank,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,pivot,streams,track_index
count,746.000000,746.000000,746.000000,746.000000,746.000000,7.460000e+02,746.000000,746.000000,746.000000,746.000000,...,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,7.460000e+02,746.000000
mean,58.872654,3.880697,3.880697,53.336461,2.262735,1.961166e+07,80.180965,93.935657,0.706966,0.651894,...,0.120531,0.196629,0.004646,0.173590,0.518285,119.525903,210036.601877,0.406166,8.657605e+06,21932.809651
std,29.059183,4.467989,4.467989,27.257769,1.286222,2.217889e+07,9.403596,56.426075,0.131187,0.151362,...,0.098505,0.203354,0.034581,0.127064,0.219565,30.352629,42140.281231,0.491446,5.646666e+06,12591.567925
min,0.000000,1.000000,1.000000,0.000000,1.000000,9.830000e+02,44.000000,1.000000,0.153000,0.111000,...,0.025900,0.000239,0.000000,0.021500,0.050300,63.476000,73813.000000,0.000000,2.676819e+06,69.000000
25%,60.000000,1.000000,1.000000,50.000000,1.000000,3.274440e+06,75.000000,46.000000,0.638250,0.557250,...,0.049425,0.047425,0.000000,0.095150,0.349250,95.819500,181837.250000,0.000000,5.107926e+06,10268.750000
50%,71.000000,1.000000,1.000000,63.000000,2.000000,1.015549e+07,81.000000,92.000000,0.724000,0.672000,...,0.082750,0.129000,0.000000,0.126500,0.512000,112.025000,204514.500000,0.000000,6.642778e+06,22034.000000
75%,77.000000,5.000000,5.000000,71.000000,3.000000,2.993942e+07,87.750000,141.000000,0.800000,0.763000,...,0.160750,0.269000,0.000010,0.207500,0.678750,139.994000,229509.750000,1.000000,1.042994e+07,32910.500000
max,90.000000,22.000000,22.000000,86.000000,9.000000,1.040598e+08,100.000000,200.000000,0.974000,0.962000,...,0.649000,0.978000,0.550000,0.792000,0.962000,212.117000,368035.000000,1.000000,4.293406e+07,44108.000000